---
title: "Review And Recommendation Of Sexual Violence Intervention Programs For LGBTQI Refugees"
output: 
  html_document
---

<Academic Paper, 13 page read>

### Introduction

Due to pervasive homophobia and transphobia that is deeply rooted in society and persecution in their countries of origin, individuals with a diverse sexual orientation flee their home countries and seek protection abroad (UNHCR, 2013). However, recent publications have exposed the barriers that asylum-seekers and refugees with diverse gender identities, such as lesbian, gay, bisexual, trans, queer, and intersex (LGBTQI), face throughout their resettlement process. A 2016 study by Amnesty International reported that “the poverty and insecurity in which many refugees find themselves in countries like Lebanon and Libya heightens the risk of sexual exploitation and gender-based violence.” (Amnesty International, 2016). Furthermore, interviews taken during the study highlighted how women, girls, and LGBTQI refugees from Central America’s Northern Triangle countries (Guatemala, El Salvador, and Honduras), fleeing high levels of violence, including physical assault and robbery, are at risk of gender-based violence both in their countries of origin and while in transit. Hence, once LGBTQI refugees arrive at a host location or temporary camps, it is critical for them to receive adequate care and protection to address the mental and physical trauma that they were exposed to. 

### Limitations of the Current Framework

However, the current focus on gender-based violence (GBV) intervention programs in forced migration settings is heteronomative and severely limited in resources. The lack of inclusive space and protective measures, as well as the lack of staff with diverse sexual orientation, highlight an urgent need for GBV and mental health reforms in resettlement camps to provide better protection for LGBTQI refugees. Furthermore, LGBTQI youths are especially vulnerable to sexual abuse and violence in their communities, as they search for a safe environment without an adequate support system (Yan, 2014). Faced with a continuous cycle of dislocation, violence, and instability, LGBTQI refugee youths often associate protection from the anonymity of urban areas, away from refugee camps (UNHCR, 2013). However, without an adequate support system in the host country and trauma interventions, LGTBQI youth refugees find themselves struggling with access to healthcare, education, and skills. 

It has been reported that LGBTQI refugees are often reluctant to seek assistance for fear of revealing their sexual orientation or gender identity to people who may subject them to further persecution (U.S Department of State, 2018). Often, this reluctancy leads to the “invisibility” of LGBTQI migrants, which further limits access to critical services including medical care and various components of resettlement programs. Hence, the current framework of resettlement programs needs to incorporate the needs of LGBTQI refugees to unmask their invisibility and provide a sustainable support system for them to reintegrate into the host community. In this paper, I challenge the current sexual violence and intervention programs for LGBTQI refugees by reviewing the key issues, current initiatives, and recommendations to address matters related to sexual violence prevention based on the social-ecological framework. 

### The Lack of Diversity and Inclusion Among Program Staff

Often, the traditional intervention and integration programs at refugee camps are heteronormative and fail to serve individuals with a diverse sexual orientation and/or gender identity, and these programs would benefit from investigative multiple pathways to resilience building (Bonanno, 2005). Many program volunteers and staff are inadequately trained to provide the unique needs of LGBTQI refugees who seek intervention. Notably, these humanitarian organizations lack the basic language to better serve the community in need. For example, the United States’ recent report on supporting LGBTQI refugees uses the term LGBTQI, thereby excluding other communities such as people who identify as queer or intersex (U.S Department of State, 2018). 

Although it may seem trivial, terminology and language is the foundation of building an inclusive community and gaining trust from the participants. In most languages worldwide, sexual orientation and gender diversity are shrouded in confusion and taboo. Many program staff unknowingly offend the very people they intend to help, addressing them with deeply offensive terms, which is inconsistent with the ‘No harm principle’ (Wessells, 2009). In order to address this issue, the Organization for Refuge, Asylum & Migration (ORAM) released a report written in different languages (Arabic, English, Farsi, French, Turkish) to provide appropriate terminology for people with diverse sexual orientations and identities (ORAM, 2016). The report’s goal is to “create a safe space and build trust with refugees, recognize inappropriate or offensive terminology, and recognize the terms refugee applicants use to identify themselves”. Often, people unknowingly use self-deprecating and derogatory words are used by LGBTQI refugees to identify themselves, evidence of the lack of respectful terminology in their own countries (Zappulla, 2018). Empowering refugees and program staff about appropriate terminology surrounding this matter is a fundamental step in establishing trust, individually and collectively. In addition to training humanitarian workers, further partnerships with local non-profits should be explored to protect LGBTQI people throughout the immigration process, in which people are often stereotyped during interviews.

### Invisibility of LGBTQI Refugees

Sexual violence is especially intensified in crisis or during an armed conflict, and people with diverse sexual orientation are especially vulnerable to invisibility in humanitarian settings. The current discussion on intervention programs primarily protects girls and young women, and tacitly excludes gender minorities from certain services and fails to provide appropriate resources to them during an emergency. The same type of prevention and response programs aimed to serve women and girls should be equally available to prevent and respond to the needs of LGBTQI communities as well, which would assist in creating a sustainable pathway to empowerment in the host country. A recent initiative, called the Sexual Violence Project, was launched by Women’s Refugee Commission in 2018 to examined the effects of sexual violence against people who have identified as male or were designated as male at birth, including cisgender heterosexual men and boys, gay and bisexual men, and transgender women and transgender men (WRC, 2018). Although data-driven evidence is limited at this stage of the program, this initiative demonstrates the growing need to provide inclusive programming in humanitarian settings for refugees. 

According to Micro Rainbow International, LGBTQI refugees suffer physical and emotional abuse, sexual harassment, and even rape in the accommodation provided by the United Kingdom government (Micro Rainbow, 2019). However, most of these episodes go unreported as refugees fear it might affect their citizenship application. As a result, many sexual assault survivors and victims tend to leave, ending up homeless and with no social support, entering a cycle of poverty and, often, sexual exploitation.  The lack of resources, support, and early intervention could lead to chronic mental health disorders, such as anxiety and depression, and could lead to self-destructing behaviors and untreated mental health disorders. Hence, the expansion of the current gender-based violence intervention programs and psychosocial support to address the needs of sexual minorities in refugee camps or migrant camps is greater than ever. 

### Issues of Domestic Violence and Honor Killings

Recent reports have claimed that domestic abuse from family members related to sexual orientation and gender identity is a common form of sexual violence (Welsh Government Social Research, 2014). LGBTQI refugees have identified multiple forms of “honor”-based violence, including “corrective” rape and forced marriage to “cure” LGBTQI people. The UK has collected interviews from gay and lesbian people being coerced or tricked by relatives into traveling to South Asian and Middle Eastern countries and forced into marriage. In these case studies, people describe not only forced marriage, but also experiencing physical violence, imprisonment, and threats to kill from family members (Welsh Government Social Research, 2013). Many current programs invest in time, money, and effort to recruit participants on anti-domestic violence programs, and these programs would benefit from including same-sex violence (mother to girls, child, male-male violence), as they already have the participants. Many current programs can slowly incorporate the idea of same-gender violence and create a safe space for participants to inquire more and raise awareness about anti-violence from family members.

In 2014, the International Federation of Red Cross reported that restoring family links activities could reduce distress and alleviate suffering during emergency responses, especially during migration (IFRC, 2014). However, this traditional resilience and protection framework is challenged in the context of LGBTQI refugees. The issue of familyhood is a unique and sensitive activity for LGBTQI refugees, as they could have experienced domestic violence, abuse, and neglect from their own family due to their sexual orientation status.
*Instead of the traditional framework of restoring family links, it would be critical for the host country to explore and adapt different methodologies to support LGBTQI refugees to feel safe and reconnect on the personal and community level about familyhood.* As much as it is important to restore family links, for LGBTQI refugees and other marginalized communities, who have purposefully separated from their family members, the psychosocial programs should aim to grieve the loss of “family”. Furthermore, when supporting LGBTQI refugees, creating a new, healthy relationship about family and internally restoring their relationships at the personal, family, and community level to keep hope alive for the future are key sustainable models (IFRC, 2014). Specifically, these programs should aim to strengthen life skills that help them make safe and healthy choices, improve communication and interaction, and increase self-confidence and self-esteem, which are critical skills for LGBTQI youths. For children who were often neglected, abused, and were raised in a toxic environment due to their sexual orientation and/or gender identity, they are especially at risk to repeat the cycle of violence at personal and community levels (Katz-Wise, S., 2016). It is imperative that LGBTQI youths are protected and feel safe at refugee settlements, especially in emergency settings, where they are neglected and easily targeted.

As mentioned earlier, the “invisibility” of LGBTQI refugees and their decision not to claim asylum on the basis of their LGBTQI status depend on the lack of preparedness at several bureaucratic levels in the host country. LGBTQI asylum seekers are expected to provide witness statements and evidence corroborating their sexual orientation or gender identity throughout their application. However, this is a life-threatening task, as it might endanger family members, previous partners, and asylum seekers themselves, especially if they are detained in refugee camps without adequate privacy (Zappulla, 2018). A 2010 report by Stonewall reported that 98% of asylum claims based on sexual orientation and/or gender identity were rejected, at this alarming rate, LGBTQI refugees are an extremely vulnerable community who are forced to go back to often violently homophobic countries, such as Uganda and Iran (Stonewall, 2010).

### Recommendations to the Host Countries 

The host countries need to prepare their societies to provide psychosocial programs that are connected with wider tasks of political, economic, and social reconstruction for social justice and inclusion. *The host countries should further collaborate with government and anti-domestic violence organizations to critically analyze the economic and social effects of domestic violence on LGBTQI refugees and create interdisciplinary programs to support survivors and raise awareness about anti-violence.* The investment into the new generation to prevent and eradicate will have a positive effect on economic and social growth, toward peace and social justice. Instead of erasing people’s experience and silencing survivors, a collaborative effort among stakeholders is critical to address the complex interplay between individual, relationship, community, and societal factors around gender-based violence and domestic violence, and provide psychosocial support to communities in need (Dahlberg LL, 2002).

### Honoring Confidentiality and Consent

One of the key issues with intervention programs in humanitarian crises is its ability to protect participants’ confidentiality and informed consent. As LGBTQI refugees are vulnerable to targeted violence and hate-crime, potential participation of programs could unintentionally out people and lead to potentially detrimental and violent responses from the community. As emphasized by Wessells, all psychosocial support work should be done to the principle of ‘Do No Harm’ to those who are supposed to benefit from any intervention, which cautions against unintentional harm that is preventable through careful planning (Wessells, 2009). As issues of power and culture inherently influence one’s ability to protect confidentiality and informed consent, organized effort that focused on participant-centered care and program is critical. The monitoring, evaluating, planning, and implementation process should be fully throughout to ensure no (re)stigmatization and trigger trauma for participants. Furthermore, these programs should be adequately equipped, including medical referrals for participants at risk. For example, the creation of unrealistic expectations by the program staff could lead to scattered and uncoordinated support, insensitivity to emergency and existing systems that can disrupt the local communities, and programs that lack capacity building and sustainability that instead encourage dependency from the participants. These unintentional harms that could have been avoided undermine the organized effort to create a safe environment to respect the confidentiality of participants (Wessells, 2009).

Often in humanitarian settings, severely underfunded organizations are unable to prioritize the needs of LGBTQI refugees in the context of other life-threatening situations, such as hunger, contagious disease, and armed conflict. Although many programs lack funding and staff to provide personalized and unique services, organizations should collaborate with the local community and initiate psychosocial activities that could be run without expensive resources. The main goal of these psychosocial activities should focus on creating the interaction between two or more individuals, and the most important resources needed are time and good communication skills (IFRC, 2014). Focusing on these inexpensive resources can help organizations overcome the challenges regarding cost. IFRC reported various frameworks and model options to strengthen resilience at a personal and community level. 

### The Psychosocial Response Model 

As outlined by IFRC, these psychosocial response models can help plan, implement, and manage a psychosocial support program from people who desperately need them to break the cycle of displacement and violence (IFRC, 2014). For example, for individuals who are at high risk who need medical support, then stand-alone psychosocial programs might provide more privacy and a safety net for the participants, due to its independence from other programs. Additionally, various social work and public health organizations and staff can collaborate to create a psychosocial plus model or integrated model, which integrates other basic needs such as food, shelter, water, clothing, or livelihood. These programs would be suitable for organizations with participants who are comfortable and feel safe to develop self-sustaining skills and resources in their host country. Among LGBTQI refugees, there is a need to identify key issues from the country of origin and provide appropriate resources in the new country, such as financial independence and empowerment, housing security, and psychotherapy to address post-traumatic stress disorder. It is critical to provide job and mentoring opportunities for survivors and victims of gender-based violence in the host country and appropriate resources for any previous trauma and mental health concerns. Intervention programs need to collaborate with local LGBTQI centers and social workers to create a sense of community and early integration into the host community through mentorship and stability (through income or school). For example, Micro Rainbow is an organization in the UK that provides housing security and skills-based training to LGBTQI refugees, along with psychological support. Specifically, the organization is working with retailer Uniqlo to offer LGBTQI asylum seekers work experience and employment training, providing clothes suitable for job interviews for those who were ready to enter the job market.

Another critical view of intervention programs questions the imposition of the host, and often Western, the country’s concept of psychosocial, power, and privilege to marginalized communities (Honwana, A., 2001). Overzealous humanitarian professionals and volunteers might intentionally or unintentionally condone local cultural practices that could lead to unstabilizing the relationship from participants. “Ill-conceived attempts to either romanticise or demonise local culture” could lead to loss of respect from local organizations, leaders, and LGBTQI refugees. Fundamentally, program practitioners should acknowledge the fluid and dynamic features of culture of the participant and the host organizations (Wessells, 2012).

### Conclusion

The information reviewed above highlights many challenges and barriers that LGBTQI refugees may face during their transition to the host country. Clearly, current programming goals and professionals need to move beyond overly simplistic and heteronormative concepts of sexual violence, post-trauma intervention, and resilience to embrace the broader costs and benefits of various dispositions and pathways. As Bonnano stated, many questions await empirical review and more research into the commonalities and differences in resilient functioning among marginalized refugees can lead to a fruitful outcome (Bonnano, 2005). As shown in the discussion above, gendered societal dynamics of exclusion and violent conflict affect LGBTQI refugees, especially youths, in various ways. There have been recent changes to peacebuilding policy and initiatives that aim to address the needs of LGBTQI refugees, such as the programs by ORAM and WRC. However, it is premature to draw conclusive evidence from these programs and there needs to be improved methods of data collection to compare and contrast the protection of LGBTQI refugees based on data-driven evidence. 

In part, the “invisibility” of LGBTQI refugees may be out of a reluctance to engage with an uncharted, sensitive field. Nonetheless, there is a clear case for bringing LGBTQI issues into peacebuilding and policymaking by taking the concerns of the most vulnerable sections of society into consideration. Lastly, examining violence and discrimination against LGBTQI refugees will help us better understand the gendered dynamics behind exclusionary politics and violence (International Alert, 2017).

### <b>Citations</b>
1. Amnesty International. (2016). Refugees Are In Urgent Need Of Protection From Sexual And Gender-based Violence. Retrieved June 30, 2020, From https://www.amnesty.org/en/latest/news/2016/11/refugees-are-in-urgent-need-of-protection-from-sexual-and-gender-based-violence/

2.General Assembly - Office Of The United Nations High Commissioner For Human Rights. (2013). Retrieved June 30, 2020, From https://www2.ohchr.org/english/bodies/hrcouncil/docs/19session/a.hrc.19.41_en.pdf

3. Honwana, A. (2001). Discussion Guide 4: Non-western Concepts Of Mental Health. In M. Loughry & A. Ager. The Refugee Experience: Psychosocial Training Module. Oxford: Refugee Studies Centre. Pp. 103-119. 

4. International Alert. (2017). Gender Sexual And Gender Minorities. ISBN: 978-1-911080-44-2

5. International Federation Of Red Cross And Red Crescent Societies(IFRC). (2014). Strengthening Resilience: A Global Selection Of Psychosocial Interventions. 

6. Katz-wise, S. L., Rosario, M., & Tsappis, M. (2016). Lesbian, Gay, Bisexual, And Transgender Youth And Family Acceptance. Pediatric Clinics Of North America, 63(6), 1011–1025. https://doi.org/10.1016/j.pcl.2016.07.005

7. Krug E, Dahlberg Ll, Mercy Ja, Zwi Ab, Lozano R, Eds. (2002). Violence-a Global Public Health Problem. World Report On Violence And Health. Geneva, Switzerland: World Health Organization. 1–56.

8. Micro Rainbow. (2019, May 26). Suffering In Silence - The Invisibility Of LGBTI Refugees. Retrieved June 30, 2020, From https://microrainbow.org/suffering-in-silence-the-invisibility-of-lgbti-refugees/

9.Organization For Refuge, Asylum & Migration (ORAM). (2016). Sexual Orientation, Gender Identity And Gender Expression: Essential Terminology For The Humanitarian Sector.

10. Stonewall. (2010). No Going Back: Lesbian, Gay, And Bisexual People In The Uk Asylum System. Retrieved June 30, 2020, From https://www.stonewall.org.uk/resources/no-going-back-2010

11. U.S Department Of State. (2018). Protecting And Assisting Lgbt Refugees. Retrieved June 30, 2020, From https://2009-2017.state.gov/j/prm/policyissues/issues/c62979.html

12. Welsh Government Social Research (2014). Barriers Faced By Lesbian, Gay, Bisexual And Transgender People In Accessing Domestic Abuse, Stalking, Harassment, And Sexual Violence Services. From https://gov.wales/sites/default/files/statistics-and-research/2019-07/140604-barriers-faced-lgbt-accessing-domestic-abuse-services-en.pdf

13. Wessells, M. (2009). Do No Harm: Toward Contextually Appropriate Psychosocial Support In International Emergencies. American Psychologist, 64(8), 842-854.

14. Wessells, M. (2012). Psychosocial Well-being And The Integration Of War-affected Children: Toward A Community Resilience Approach. In I. Derluyn, C. Mels, S. Parmentier, & W. Vandenhole (Eds.), Re-member: Rehabilitation, Reintegration And Reconciliation Of War-affected Children. Cambridge/Antwerp/Portland: Intersentia.

15. Womens Refugee Commission. (2018). Sexual Violence Against Men And Boys. Retrieved June 30, 2020, From https://www.womensrefugeecommission.org/focus-areas/sexual-gender-based-violence/sexual-violence-against-men-and-boys/

16. Yan, Shanshan. (2014). Through An Intersectionality Lens: Service Provider Views On The Sexual Health Needs Of Racialized LGBTQ Youth In Toronto. Theses And Dissertations (Comprehensive). https://scholars.wlu.ca/etd/1643

17. Zappulla, A. C. (2018). Forgotten Twice: The Untold Story Of Lgbt Refugees. Retrieved June 30, 2020, From https://www.weforum.org/agenda/2018/01/forgotten-twice-lgbt-refugees/
