---
title: "Project Proposal"
output: 
  html_document:
    toc: true
    toc_float: true
---

### <b>A.	NGO and Project Name</b>
The project, menstrual WASH  in Accham Schools (WAS), is for adolescent girls who attend schools in Accham District in Western Nepal. The project is supported by UNICEF Nepal  and the Accham School District.  
  
### <b>B.	Context </b>
The practice of chhaupadi, traditional seclusion of menstruating women, continues to endanger young girls and women in Nepal, despite the ban by the Nepal Supreme court in 2005. In Hindu culture, menstruating Hindu women are not allowed in the kitchen and prayer room, have limited access to medicine and running water, lack access to sanitary pads, have to hand-wash clothes and scrub the floor they slept on during their period . Since menstruating women have to sleep outside of the house where men sleep, this increases the vulnerability of girls to violence, including attacks from wild animals and assault at night.  
  
Furthermore, the practice of chhaupadi increases the vulnerability of pregnant mothers and their newborns as they are expected to stay in the unhygienic shed during the time of childbirth, which can lead to maternal and infant death due to preventable complications, such as excessive bleeding and septic shock.  Thus, an early intervention program in menstrual hygiene education can empower young girls with accurate menstrual information and prevent their exposure to gender-based violence and stigma in the future.   
  
Accham is a remote and underdeveloped district in Western Nepal. The literacy rate (ages 5+) for Achham district is 56%, compared to the national literacy rate in Nepal of 66%. 18% of households have electricity and 48% have toilets, below the household national average of 67% in electricity and 62% in toilets. In 2011, Accham had 621 households (population = 3124) and 421 girls between the ages of 10–19, and the average household monthly income was $143.     
  
In 2016, 77 out of 107 (72%) girls in Accham reported they were not able to sleep in the same house as the rest of the family due to chhaupadi.  Furthermore, they reported the fear of leakage and not feeling ‘well’ at school, which affected their ability to participate in lessons or sports activities. The study concluded that many girls experience shame, fear, confusion, lack of accurate information, advice and support with regards to their menstruation.   
  
The program’s goal is to provide girls in Accham district with accurate menstrual hygiene education, increase access to hygienic bathrooms and running water, and increase knowledge of community resources. The program will use children-friendly activities such as songs, printed materials (that will be left at schools to protect the privacy of students), and peer educators to increase participant’s access and knowledge of menstrual WASH (water, sanitation, and hygiene) objectives.   
  
When I studied abroad in Nepal in 2014, my host-family practiced chhaupadi, as a foreign student I respected their tradition, but I still experienced shame and fear that chhaupadi was exacerbating. When I visited different parts of the country, chhaupadi and its inconveniences at school, work, and home were a frequent conversation topic among young Nepalese girls and women in my community. Through this program, in collaboration with UNICEF Nepal, I hope to prioritize the needs of young girls and offer them solutions and accurate information to reduce stigma and ensure the well-being of girls.   
  
### <b>C.	Expected Results</b>
The school site is an ideal intervention setting for providing information and the impetus for change opportunities, especially for girls whose families practice traditional chhaupadi at home. The program aims to reduce the prevalence of chhaupadi among adolescents (between 12-19 years old) girls in Accham, particularly the practice of menstruating girls to sleep outside, from 72% to 20% by the end of the 2-year program. Also, the program will increase the number of girls-only toilets from 4 to 8 by the end of the program.  Participants (female educators, peer educators, and participants) will have increased knowledge of the menstrual cycle and access to safer and more accountable WASH programming and resources for girls in their communities.   

Young girl’s access to menstrual hygiene education is related to vulnerability to gender-based violence. Even with minimal resources, implementation of the WASH education can make substantial contributions to limit chhaupadi practices, the safety of women and girls, accountability to affected communities and overall quality of programming in emergencies.   
  
### <b>D. Project Implementation & Monitoring</b>

#### <b>Project implementation</b>

The project relies on Bandura’s social learning  (learning from role models, self-efficacy, and increased access) as a theory of behavior change and Prochaska’s transtheoretical model  of behavior change, which assesses an individual's readiness to act on a new healthier behavior, and provides strategies, or processes of change to guide the individual. These approaches are beneficial to achieve sustainable solutions that involve local stakeholders regarding chhaupadi and menstrual WASH. The program will assess the needs and preferences of girls in Accham, the prevalence of chhaupadi practice among adolescent girls, identify sites that girls indicated as risky or unsafe at home and at school, provide accurate information on menstrual WASH knowledge to adolescent girls and educators at school, and improve community resources that are safe for girls.  
  

#### <b>Before the program</b> 

-	Needs Assessment of girl’s knowledge about menstrual hygiene and community resources.  
-	Recruit female educators, peer educators, participants.  
-	Identify other stakeholders (parents, local WASH advocate groups).  
  
*1st quarter*

-	Conduct focus group discussions with girls between 12-19 years old in Accham district (n= 2)  to identify their needs regarding menstrual hygiene, chhaupadi prevalence, and their preferences.  
-	Conduct focus groups with female educators on school WASH facilities and their management (running water, girls-only latrines).  
-	Develop a curriculum on menstrual WASH program.  
  
*2nd quarter (end of 1st year)*  

-	Visit and identify unsafe locations that girls indicated as risky and insecure locations for menstrual hygiene, including sites they stay during chhaupadi and school facilities.  
-	Increase advocacy for separate latrine blocks for girls and boys in schools, in addition to stronger monitoring and management by the school administration, parents, and community leaders (i.e. religious leaders from Brahmin caste).  
-	Train female educators and peer educators based on the curriculum.    
  
*3rd quarter*  

-	Conduct 10 sessions with girls under 17 at each school (1 hour/ week) in Accham to better understand menstrual hygiene, safety concerns related to distances between shelter, waterpoints, family latrines, and school facilities using children-friendly activities such as songs and printouts.   
-	Slowly promote community awareness on reducing chhaupadi practice at home through increased participation of peer educators, female educators, WASH management committees at school through awareness-raising and opening of entry points in communities.  
  
*Final quarter (end of 2nd year)*  

-	Measure girl’s change of knowledge and attitude towards menstrual hygiene, WASH knowledge, the prevalence of chhaupadi practices at home, resources and their safety in school and community.   
-	Identify sites that still need improvement in Accham, both schools and homes, that girls still indicate as risky and insecure locations before and after the 3rd quarter.   
-	Identify persisting issues in these locations (lack of infrastructure, caste system) and engage with other WASH-related governance structures to address the problem and offer sustainable solutions to meet menstrual WASH objectives.   

### <b>Monitoring and Evaluation</b> 

-	Participants’ (adolescent girls and female educators) ability to accurately identify menstrual hygiene and WASH knowledge to measure the change of behavior and attitude after the program sessions.  
-	Peer educators and female educator’s ability to correctly identify school resources for girls who are at risk of gender-based violence due to chhaupadi or menstrual hygiene to measure their ability to identify GBV risk and mentor peers.  
-	The number of private latrines available at schools with running water (for girls to wash their menstrual cloths) and sanitary places to dispose of their used pads, the number of schools that provide education and support for young girls to measure the change in school settings to provide safe space for girls.  
-	The number of sites that girls identify as risky or unsafe to go during their menstrual cycle at home and school, to measure the change in the number of safer facilities/ latrines.  

### <b>Citations</b>
Bandura, A. (1995). Social foundations of thought and action: a social cognitive theory. Englewood Cliffs, NJ: Prenctice Hall.  
CBS (2012) National Population and Housing Census 2011 (National Report). Kathmandu, Nepal: Government of Nepal, National Planning Commission Secretariat, Central Bureau of Statistics. Available at: https://unstats.un.org/unsd/demographic-social/census/documents/Nepal/Nepal-Census-2011-Vol1.pdf.  
DEO (2014) Flash Report II total enrollment 2070. Achham, Nepal: District Education Office Achham, Ministry of Education, Government of Nepal.  
Gautam, G. (2019, March 14). 3 strategies to address menstruation taboos for girls in Nepal. Retrieved from https://www.brookings.edu/blog/education-plus-development/2018/09/21/3-strategies-to-address-menstruation-taboos-for-girls-in-nepal  
GBV Guidelines (2018). Practice Brief: Improving safety for women and girls GBV risk mitigation in humanitarian response: practical examples from multiple field settings Sectors: camp management, health, education, food security, nutrition, shelter and WASH Countries: Ethiopia, Nigeria, Syria, Somalia and South Sudan. Access at: https://gbvguidelines.org/wp/wp-content/uploads/2018/12/GBV-Practice-Brief-20181126-web.pdf   
Amatya P. (2015) Maternal and Child Health Care in Chhaupadi Pratha, Social seclusion of mother and child after delivery in Achham, Nepal. Public Health Research Series: 22.  
Prochaska, J. O., & Velicer, W. F. (1997). The Transtheoretical Model of Health Behavior Change. S.l.: s.n.  
UNICEF Nepal (2018, April) Analysis of Menstrual Hygiene Practices in Nepal: The role of WASH in Schools Programme for Girls Education 2016. Available at: https://www.unicef.org/nepal/sites/unicef.org.nepal/files/2018-07/607531012327148357-analysis-of-menstrual-hygiene-practices-in-nepal.pdf  
UNICEF. Advocacy and Capacity Building for MHM through WASH in Schools. www.wins4girls.com. Retrieved April 2, 2020, from http://www.wins4girls.org/countries/nepal.html
Vaughn, E. (2019, December 17). Menstrual Huts Are Illegal In Nepal. So Why Are Women Still Dying In Them? Retrieved April 2, 2020, from https://www.npr.org/sections/goatsandsoda/2019/12/17/787808530/menstrual-huts-are-illegal-in-nepal-so-why-are-women-still-dying-in-them  

