---
title: " Protecting Human Rights in the Age of Digital Surveillance"
author: "Michelle Lee"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

<Academic Paper, 5 page read>

### Introduction

Recently, the rise of technology has created an opportunity for people to stay connected and gain information through social media, such as Facebook and Google. As these platforms have become an integral part of our daily lives, there are consequential adverse impacts on human rights, especially on marginalized communities. Digital surveillance is the use of digital technology to control others, citizens, and the life of a nation (Korstanje, 2018). More specifically, segregated surveillance refers to government-sponsored digital surveillance programs that target ethnic or religious minorities to submit to monitoring and data collection, while ignoring the majority group (Buckley, 2019). Some countries like China and Myanmar are using too much technology to systematically campaign against religious and ethnic minorities, which has led to a profound impact on human rights: (1) digital surveillance threatens the existence of marginalized communities and (2) violates the rights to freedom of expression, information, and participation (Ambay, 2019). Due to the clandestine nature of digital surveillance, high-tech methods such as satellite images and open source data could be explored to estimate mortality, forced incarceration, and displacement rates. Without proper documentation, governance models based on China and alike will challenge democracy and human freedom that is dramatically different than that of today.
Certainly, there are benefits and important roles that technology continues to play in assisting individuals in humanitarian settings, such as blockchain technology to register and distribute aid to refugees by the United Nations High Commissioner and the World Food Program (Beduschi, 2019). However, governments like the Chinese Communist Party are using technology as a new governance tool to gain control over certain populations through increasingly intrusive policing systems. Mass surveillance systems allow governments to exclude people from reaping the benefits of technology (Rohingya Project, 2018), while
1

 Protecting Human Rights in the Age of Digital Surveillance
simultaneously identifying these populations to discriminate against them. For example, surveys allowed the Chinese government to efficiently identify and discriminate against the Uyghurs, as they became more visible through the internet (Byler, 2019). Over the past decade, China's western Xinjiang region, home to the Uyghurs, has become a frontline laboratory for data-driven surveillance (Qiang, 2019). Thousands of government-owned facial-recognition cameras are ubiquitous in Xinjiang in villages, mosques, and on roads (Buckley, 2019), where GPS tracking, voice and facial recognition, and personal information are then stored and analyzed at government facilities (Leibold, 2020). A more overt form of digital surveillance is the mandated surveillance app, called the “Cleannet Bodyguard” - which gathers information from Weibo (China’s Twitter), IMEI numbers, SIM card data, WIFI login data - in which local police carry out spot checks to make sure that the app has been installed on Uyghur residents (Leibold, 2020). These pieces of information have been used by the Chinese government to identify people to be sent to the indoctrination internment camps or arrested (Buckley, 2019). Furthermore, the methods employed in Xinjiang could lead to the nationwide and global implementation of similar "predictive-policing tactics'' (Qiang, 2019), as there are many countries that would find these surveillance methods appealing. Recently, the Malaysian government adopted China’s surveillance system with facial-recognition cameras and artificial intelligence-powered technology to law enforcement agencies, raising concerns for China’s growing international dominance and the spread of digital surveillance tactics used by high-tech authoritarian governments (Tan, 2019).
In 2018, the United Nations estimated that more than 1 million Uyghurs and Muslim minorities are forced into these internment camps, which is shrouded in secrecy with forced labor and sterilization, severe restrictions of movement, expression, and religion, all violating basic human rights (Committee on the Elimination of Racial Discrimination, 2018) (Alecci, 2020). In China, the main challenges to documenting human rights violations are the
2

 Protecting Human Rights in the Age of Digital Surveillance
censorship and the lack of access to internal government documents. With access to internet cut-off, it is difficult for Uyghurs to share their experiences to each other or to international organizations without alerting the Chinese government (Leibold, 2020). While the exact number of people held in internment camps are unknown, international organizations are using open-source data such as satellite imagery, official statistics, and a range of authoritative reports and academic studies to better estimate human rights abuses in Xinjiang region (The Xinjiang Data Project, 2020). While satellite imagery assists in developing 3D models of the internment camps, reports and investment documents indicate the growth of digital surveillance, and the personal recounts of police brutality against Uyghur muslims in Xinjiang can help document the implications of digital state on human rights violations. While the traditional epidemiological methods to document human rights violations might not be feasible in censored areas, mixed approaches using technology such as satellite images and encrypted messaging systems could be adopted to document evidence against high-tech authoritarian governments.
Social media has also been widely employed by governments as a tool for ethnic cleansing. In Myanmar, anti-Muslim campaigns are pervasive across the country, politically led by the military and socially implemented by Buddhist nationalists (OHCHR 2018). Recently, Myanmar military officials adopted Facebook to promote anti-Rohingya propaganda, which led to mass rape, forced migration, and genocide (Mozur 2018). The military-driven campaign on Facebook included hundreds of military officials who created fake names, news, and entertainment pages and then posted inflammatory posts portraying Rohingya as terrorists (Mozur 2018). In 2017, the military spread disinformation on Facebook to both Muslim and Buddhist groups that an attack from the other side was imminent. The goal of this campaign was to incite violence and generate fear and vulnerability that would legitimize the military’s intervention as a form of protection (Mozur
3

 Protecting Human Rights in the Age of Digital Surveillance
2018). As a result, recent surveys show that more than 647,000 Rohingya have fled from Myanmar to Bangladesh and 6,700 were killed during the violent attacks in Myanmar (Médecins Sans Frontières 2017). Without much accountability, Facebook continues to be the platform where officials use to spread hate speech and disinformation against the Rohingya people, which ultimately has “a negative impact on freedom of expression, assembly and association for Myanmar’s most vulnerable users” (Stevenson 2018).
In addition to campaigns on Facebook, military officials are now restricting internet access in Rakhine State, where the goal is to disrupt humanitarian aid and curtail the flow of information to Rohingya people by international organizations (Human Rights Watch 2019). Furthermore, Rohingya people are required to sign up to a digitized National Verification Card that effectively identifies them as a foreigner and subsequently denies them of Myanmar citizenship rights (Fortify Rights 2020), which is similar to the digital surveillance tactic using citizenship cards in Xinjiang, China. However, unlike China where severe censorship hinders human rights documentation, several epidemiological methods can be used to document human rights violations including, surveys, interviews, satellite imagery, government documents, and social media analysis. In the past, surveys and interviews from the refugee camps in Cox's Bazar, Bangladesh have helped international organizations better estimate mortality and displacement rates due to violence (Médecins Sans Frontières 2017). Also, investigations by reporters and reputable international organizations have gained significant global attention to the Rohingya genocide through graphic images, videos, and stories from the Rakhine State (Krug 2018). Furthermore, algorithm models with online hate detection with 92% accuracy level provides an unique and innovative approach to documenting occurrences of military-sponsored posts and disinformation on Facebook (Salminen 2020). Along with satellite images that show displacement patterns, these
4

 Protecting Human Rights in the Age of Digital Surveillance
information can help document and condemn the military-driven campaigns to incite violence through social media
Like their Western counterparts, people in China and Myanmar are complicit in this information state - people often believe that invasive surveillance is limited only to a deserving (“evil” and “criminals”) group. In the comfort of this notion, the majority tacitly consents to abuse of power (Greenwald 2014). Yet for marginal populations, such as the Uyghurs and Rohingyas, surveillance is an unwelcome and repressive tool used by the government to incite violence and deprive them of basic human rights. In areas with severe censorship, such as China, open-source data and satellite images can help us document ongoing human rights violations. In areas with some access, such as Myanmar, a mixed method of traditional epidemiology methods (surveys, interviews), satellite images, and algorithm models can detect military-sponsored tactics, mortality, and displacement rates due to violence. Without proper documentation and accountability of human rights violations in digital surveillance, segregated surveillance continues to pose as a threat to the future of governance, democracy, and human rights. Future studies should examine effective prevention methods premised on accountability and sustainable solutions to protect vulnerable populations from the most dangerous application of digital surveillance that threatens human rights.
5

 Word count:1401
Protecting Human Rights in the Age of Digital Surveillance
References
Alecci. (2020). ICC complaint alleging Uighur genocide cites China Cables as evidence. International Consortium of Investigative Journalists. https://www.icij.org/investigations/china-cables/icc-complaint-alleging-uighur-genocide-cites -china-cables-as-evidence/
Ambay et al (2019). Dystopia is now: Digital authoritarianism and human rights in Asia. Global Campus Open Knowledge Repository. http://doi.org/20.500.11825/1575
Buckley. (2019). How China Uses High-Tech Surveillance to Subdue Minorities. The New York Times. https://www.nytimes.com/2019/05/22/world/asia/china-surveillance-xinjiang.html
Committee on the Elimination of Racial Discrimination. (2018). United Nations.
https://tbinternet.ohchr.org/Treaties/CERD/Shared%20Documents/CHN/CERD_C_CHN_CO _14-17_32237_E.pdf
Greenwald. (2014). No Place to Hide: Edward Snowden, the NSA, and the U.S. Surveillance State. Signal, McLelland & Stewart.
Gregory, Sam. (2019). Cameras Everywhere Revisited: How Digital Technologies and Social Media Aid and Inhibit Human Rights Documentation and Advocacy. Journal of Human Rights Practice. 11. 1-20. 10.1093/jhuman/huz022.
Human Rights Watch. (2019). Myanmar: Crimes Against Rohingya Go Unpunished.
https://www.hrw.org/news/2019/08/22/myanmar-crimes-against-rohingya-go-unpunished
James Leibold. (2020). Surveillance in China’s Xinjiang Region: Ethnic Sorting, Coercion, and Inducement, Journal of Contemporary China, 29:121, 46-60, DOI: 10.1080/10670564.2019.1621529
Krug F. (2018). AP finds evidence for graves, Rohingya massacre in Myanmar. https://www.npr.org/sections/thetwo-way/2018/02/01/582323591/ap-investigation-details-sho cking-massacre-mass-graves-of-myanmar-rohingya (Links to an external site.) (Links to an external site.)
Kumar, S. (2020). Digital Surveillance: Implications on Human Rights. In Human Rights in 21st Century: Issues & Emerging Trends. Blue Rose.
Maximiliano Korstanje. (2018). Technology and Terror. Encyclopedia of Information Science and Technology, Fourth Edition. 10.4018/978-1-5225-2255-3.ch316
Médecins Sans Frontières. (2017).MSF surveys estimate that at least 6,700 Rohingya were killed during the attacks in Myanmar. https://www.msf.org/myanmarbangladesh-msf-surveys-estimate-least-6700-rohingya-were-ki lled-during-attacks-myanmar
         6

 Protecting Human Rights in the Age of Digital Surveillance
Mozur, Paul. (2018). A Genocide Incited on Facebook, With Posts From Myanmar’s Military. New York Times. https://www.nytimes.com/2018/10/15/technology/myanmar-facebook-genocide.html
Salminen, J., Hopf, M., Chowdhury, S.A. et al. Developing an online hate classifier for multiple social media platforms. Hum. Cent. Comput. Inf. Sci. 10, 1 (2020). https://doi.org/10.1186/s13673-019-0205-6
Tan C. (2018). Malaysian police adopt Chinese AI surveillance technology. Nikkei Asian Review.
The Xinjiang Data Project. (2020). The Australian Strategic Policy Institute. https://xjdp.aspi.org.au/about.
United Nations Human Rights Council. (2018). Statement by Mr. Marzuki Darusman, Chairperson of the United Nations Independent International Fact-Finding Mission on Myanmar, at the Security Council. https://www.ohchr.org/EN/HRBodies/HRC/Pages/NewsDetail.aspx?NewsID=23778&LangI D=E
   7
